[nanobot]
config_version = 1

[logging]
level = "DEBUG"

[database]
connection = "build/nanobot.db"

[valve]
path = "src/table.tsv"

[actions.reload]
label = "Reload from Google Sheet"
commands = [
  ["make", "clean", "all"]
]
